import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Avatar } from "~/components/atoms/avatar";
import { TwoColumeTemplate } from "~/components/templates/two-colume";

import styles from "~/pages/index.module.scss";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TwoColumeTemplate
          left={<div>Wow</div>}
          right={<div>Unbelievable</div>}
        />
      </main>
    </div>
  );
};

export default Home;
